// Auto-generated from NFC&ATC data_viewer.html — 696 entries
export interface NfcCode { code: string; labelEn: string; labelFr: string }

export const NFC_CODES: NfcCode[] = [
  { code: "A", labelEn: "Oral Solid Ordinary", labelFr: "Solide Oral Ordinaire" },
  { code: "AA", labelEn: "Oral Solid Ordinary Tablets", labelFr: "Comprimés Solide Oral Ordinaire" },
  { code: "AAA", labelEn: "Oral Solid Ordinary Tablets", labelFr: "Comprimés Solide Oral Ordinaire" },
  { code: "AAB", labelEn: "Oral Solid Ordinary Orally Disintegrating Tablets", labelFr: "Comprimés Oro-Dispersibles Solide Oral Ordinaire" },
  { code: "AAE", labelEn: "Oral Solid Ordinary Buccal Tablets", labelFr: "Comprimés Buccaux Solide Oral Ordinaire" },
  { code: "AAF", labelEn: "Oral Solid Ordinary Sublingual Tablets", labelFr: "Comprimés Sublinguaux Solide Oral Ordinaire" },
  { code: "AAG", labelEn: "Oral Solid Ordinary Chewable Tablets", labelFr: "Comprimés à Croquer Solide Oral Ordinaire" },
  { code: "AAH", labelEn: "Oral Solid Ordinary Effervescent Tablets", labelFr: "Comprimés Effervescents Solide Oral Ordinaire" },
  { code: "AAJ", labelEn: "Oral Solid Ordinary Layered Tablets", labelFr: "Comprimés à Couches Solide Oral Ordinaire" },
  { code: "AAK", labelEn: "Oral Solid Ordinary Soluble Tablets", labelFr: "Comprimés Solubles Solide Oral Ordinaire" },
  { code: "AAY", labelEn: "Oral Solid Ordinary Other Tablets", labelFr: "Autres Comprimés Solide Oral Ordinaire" },
  { code: "AAZ", labelEn: "Oral Solid Ordinary Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Solide Oral Ordinaire" },
  { code: "AB", labelEn: "Oral Solid Ordinary Coated Tablets", labelFr: "Comprimés Enrobés Solide Oral Ordinaire" },
  { code: "ABA", labelEn: "Oral Solid Ordinary Coated Tablets", labelFr: "Comprimés Enrobés Solide Oral Ordinaire" },
  { code: "ABB", labelEn: "Oral Solid Ordinary Gelatin-Coated Tablets", labelFr: "Comprimés Enrobés de Gélatine Solide Oral Ordinaire" },
  { code: "ABC", labelEn: "Oral Solid Ordinary Film-Coated Tablets", labelFr: "Comprimés Enrobés de Film Solide Oral Ordinaire" },
  { code: "ABD", labelEn: "Oral Solid Ordinary Enteric-Coated Tablets", labelFr: "Comprimés Enrobés Gastro-Résistants Solide Oral Ordinaire" },
  { code: "ABF", labelEn: "Oral Solid Ordinary Sublingual Coated Tablets", labelFr: "Comprimés Sublinguaux Enrobés Solide Oral Ordinaire" },
  { code: "ABG", labelEn: "Oral Solid Ordinary Chewable Coated Tablets", labelFr: "Comprimés à Croquer Enrobés Solide Oral Ordinaire" },
  { code: "ABY", labelEn: "Oral Solid Ordinary Other Coated Tablets", labelFr: "Autres Comprimés Enrobés Solide Oral Ordinaire" },
  { code: "ABZ", labelEn: "Oral Solid Ordinary Combination Pack Coated Tablets", labelFr: "Pack Combiné de Comprimés Enrobés Solide Oral Ordinaire" },
  { code: "AC", labelEn: "Oral Solid Ordinary Capsules", labelFr: "Capsules Solide Oral Ordinaire" },
  { code: "ACA", labelEn: "Oral Solid Ordinary Capsules", labelFr: "Capsules Solide Oral Ordinaire" },
  { code: "ACD", labelEn: "Oral Solid Ordinary Enteric-Coated Capsules", labelFr: "Capsules Gastro-Résistantes Solide Oral Ordinaire" },
  { code: "ACE", labelEn: "Oral Solid Ordinary Buccal Capsules", labelFr: "Capsules Buccales Solide Oral Ordinaire" },
  { code: "ACF", labelEn: "Oral Solid Ordinary Biting Capsules", labelFr: "Capsules à Mordre Solide Oral Ordinaire" },
  { code: "ACG", labelEn: "Oral Solid Ordinary Chewable Capsules", labelFr: "Capsules à Croquer Solide Oral Ordinaire" },
  { code: "ACS", labelEn: "Oral Solid Ordinary Cachets", labelFr: "Cachets Solide Oral Ordinaire" },
  { code: "ACY", labelEn: "Oral Solid Ordinary Other Capsules", labelFr: "Autres Capsules Solide Oral Ordinaire" },
  { code: "ACZ", labelEn: "Oral Solid Ordinary Combination Pack Capsules", labelFr: "Pack Combiné de Capsules Solide Oral Ordinaire" },
  { code: "AD", labelEn: "Oral Solid Ordinary Special Forms", labelFr: "Formes Spéciales Solide Oral Ordinaire" },
  { code: "ADD", labelEn: "Oral Solid Ordinary Pellets", labelFr: "Granules Solide Oral Ordinaire" },
  { code: "ADE", labelEn: "Oral Solid Ordinary Lozenges", labelFr: "Pastilles Solide Oral Ordinaire" },
  { code: "ADF", labelEn: "Oral Solid Ordinary Chewing Gum", labelFr: "Gomme à Mâcher Solide Oral Ordinaire" },
  { code: "ADG", labelEn: "Oral Solid Sweets/Candy/Bonbons", labelFr: "Bonbons/Sucreries Solide Oral Ordinaire" },
  { code: "ADP", labelEn: "Oral Solid Ordinary Cubes", labelFr: "Cubes Solide Oral Ordinaire" },
  { code: "ADQ", labelEn: "Oral Solid Ordinary Cakes/Chocolate/Bars/Biscuits", labelFr: "Gâteaux/Chocolats/Barres/Biscuits Solide Oral Ordinaire" },
  { code: "ADR", labelEn: "Oral Solid Ordinary Globules", labelFr: "Globules Solide Oral Ordinaire" },
  { code: "ADY", labelEn: "Oral Solid Ordinary Other Special Forms", labelFr: "Autres Formes Spéciales Solide Oral Ordinaire" },
  { code: "ADZ", labelEn: "Oral Solid Ordinary Combination Pack Special Forms", labelFr: "Pack Combiné de Formes Spéciales Solide Oral Ordinaire" },
  { code: "AE", labelEn: "Oral Solid Ordinary Powders/Granules", labelFr: "Poudres/Granules Solide Oral Ordinaire" },
  { code: "AEA", labelEn: "Oral Solid Ordinary Powders", labelFr: "Poudres Solide Oral Ordinaire" },
  { code: "AEB", labelEn: "Oral Solid Ordinary Granules", labelFr: "Granules Solide Oral Ordinaire" },
  { code: "AEF", labelEn: "Oral Solid Ordinary Sublingual Powders/Granules", labelFr: "Poudres/Granules Sublinguaux Solide Oral Ordinaire" },
  { code: "AEP", labelEn: "Oral Solid Ordinary Unit Dose Powders", labelFr: "Poudres Unidose Solide Oral Ordinaire" },
  { code: "AEY", labelEn: "Oral Solid Ordinary Other Powders/Granules", labelFr: "Autres Poudres/Granules Solide Oral Ordinaire" },
  { code: "AEZ", labelEn: "Oral Solid Ordinary Combination Pack Powders/Granules", labelFr: "Pack Combiné de Poudres/Granules Solide Oral Ordinaire" },
  { code: "AS", labelEn: "Oral Solid Ordinary Ointments", labelFr: "Onguent Solide Oral Ordinaire" },
  { code: "ASB", labelEn: "Oral Solid Ordinary Pastes", labelFr: "Pâte Solide Oral Ordinaire" },
  { code: "AY", labelEn: "Oral Solid Ordinary Other Special Forms", labelFr: "Autres Formes Spéciales Solide Oral Ordinaire" },
  { code: "AYG", labelEn: "Oral Solid Ordinary Food Ready to Eat", labelFr: "Nourriture Prête à Manger Solide Oral Ordinaire" },
  { code: "AYH", labelEn: "Oral Solid Ordinary Food not Ready to Eat", labelFr: "Nourriture Non Prête à Manger Solide Oral Ordinaire" },
  { code: "AYZ", labelEn: "Oral Solid Ordinary Combination Pack Other Special Forms", labelFr: "Pack Combiné d'Autres Formes Spéciales Solide Oral Ordinaire" },
  { code: "B", labelEn: "Oral Solid Retard", labelFr: "Solide Oral Retard" },
  { code: "BA", labelEn: "Oral Solid Retard Tablets", labelFr: "Comprimés Solide Oral Retard" },
  { code: "BAA", labelEn: "Oral Solid Retard Tablets", labelFr: "Comprimés Solide Oral Retard" },
  { code: "BAB", labelEn: "Oral Solid Retard Orally Disintegrating Tablets", labelFr: "Comprimés Orally Dispersibles Solide Oral Retard" },
  { code: "BAE", labelEn: "Oral Solid Retard Buccal Tablets", labelFr: "Comprimés Buccaux Solide Oral Retard" },
  { code: "BAJ", labelEn: "Oral Solid Retard Layered Tablets", labelFr: "Comprimés à Couches Solide Oral Retard" },
  { code: "BAY", labelEn: "Oral Solid Retard Other Tablets", labelFr: "Autres Comprimés Solide Oral Retard" },
  { code: "BAZ", labelEn: "Oral Solid Retard Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Solide Oral Retard" },
  { code: "BB", labelEn: "Oral Solid Retard Coated Tablets", labelFr: "Comprimés Enrobés Solide Oral Retard" },
  { code: "BBA", labelEn: "Oral Solid Retard Coated Tablets", labelFr: "Comprimés Enrobés Solide Oral Retard" },
  { code: "BBC", labelEn: "Oral Solid Retard Film-Coated Tablets", labelFr: "Comprimés Enrobés de Film Solide Oral Retard" },
  { code: "BBD", labelEn: "Oral Solid Retard Enteric-Coated Tablets", labelFr: "Comprimés Enrobés Gastro-Résistants Solide Oral Retard" },
  { code: "BBN", labelEn: "Oral Solid Retard Membrane-Coated Tablets", labelFr: "Comprimés Enrobés à Membrane Solide Oral Retard" },
  { code: "BBY", labelEn: "Oral Solid Retard Other Coated Tablets", labelFr: "Autres Comprimés Enrobés Solide Oral Retard" },
  { code: "BBZ", labelEn: "Oral Solid Retard Combination Pack Coated Tablets", labelFr: "Pack Combiné de Comprimés Enrobés Solide Oral Retard" },
  { code: "BC", labelEn: "Oral Solid Retard Capsules", labelFr: "Capsules Solide Oral Retard" },
  { code: "BCA", labelEn: "Oral Solid Retard Capsules", labelFr: "Capsules Solide Oral Retard" },
  { code: "BCN", labelEn: "Oral Solid Retard Membrane Capsules", labelFr: "Capsules à Membrane Solide Oral Retard" },
  { code: "BCY", labelEn: "Oral Solid Retard Other Capsules", labelFr: "Autres Capsules Solide Oral Retard" },
  { code: "BCZ", labelEn: "Oral Solid Retard Combination Pack Capsules", labelFr: "Pack Combiné de Capsules Solide Oral Retard" },
  { code: "BD", labelEn: "Oral Solid Retard Solid Special Forms", labelFr: "Formes Spéciales Solide Oral Retard" },
  { code: "BDY", labelEn: "Oral Solid Retard Other Special Solid Forms", labelFr: "Autres Formes Spéciales Solide Oral Retard" },
  { code: "BE", labelEn: "Oral Solid Retard Powders/Granules", labelFr: "Poudres/Granules Solide Oral Retard" },
  { code: "BEA", labelEn: "Oral Solid Retard Powders", labelFr: "Poudres Solide Oral Retard" },
  { code: "BEB", labelEn: "Oral Solid Retard Granules", labelFr: "Granules Solide Oral Retard" },
  { code: "BEP", labelEn: "Oral Solid Retard Unit Dose Powders", labelFr: "Poudres Unidose Solide Oral Retard" },
  { code: "BEY", labelEn: "Oral Solid Retard Other Powders/Granules", labelFr: "Autres Poudres/Granules Solide Oral Retard" },
  { code: "D", labelEn: "Oral Liquid Ordinary", labelFr: "Liquide Oral Ordinaire" },
  { code: "DD", labelEn: "Oral Liquid Ordinary Special Forms", labelFr: "Formes Spéciales Liquide Oral Ordinaire" },
  { code: "DDY", labelEn: "Oral Liquid Ordinary Other Solid Special Forms", labelFr: "Autres Formes Spéciales Liquide Oral Ordinaire" },
  { code: "DE", labelEn: "Oral Liquid Ordinary Powders/Granules", labelFr: "Poudres/Granules Liquide Oral Ordinaire" },
  { code: "DEH", labelEn: "Oral Liquid Ordinary Effervescent Powders/Granules", labelFr: "Poudres/Granules Effervescentes Liquide Oral Ordinaire" },
  { code: "DEK", labelEn: "Oral Liquid Ordinary Soluble Powders", labelFr: "Poudres Solubles Liquide Oral Ordinaire" },
  { code: "DEP", labelEn: "Oral Liquid Ordinary Unit Dose Powders", labelFr: "Poudres Unidose Liquide Oral Ordinaire" },
  { code: "DEY", labelEn: "Oral Liquid Ordinary Other Powders/Granules", labelFr: "Autres Poudres/Granules Liquide Oral Ordinaire" },
  { code: "DEZ", labelEn: "Oral Liquid Ordinary Combination Pack Powders/Granules", labelFr: "Pack Combiné de Poudres/Granules Liquide Oral Ordinaire" },
  { code: "DG", labelEn: "Oral Liquid Ordinary Liquids", labelFr: "Liquides Ordinaires Liquide Oral" },
  { code: "DGA", labelEn: "Oral Liquid Ordinary Liquids", labelFr: "Liquides Ordinaires Liquide Oral" },
  { code: "DGB", labelEn: "Oral Liquid Ordinary Drops", labelFr: "Gouttes Liquide Oral Ordinaire" },
  { code: "DGC", labelEn: "Oral Liquid Sprays without Gas", labelFr: "Sprays Sans Gaz Liquide Oral Ordinaire" },
  { code: "DGF", labelEn: "Oral Liquid Ordinary Sublingual Liquids", labelFr: "Liquides Sublinguaux Liquide Oral Ordinaire" },
  { code: "DGH", labelEn: "Oral Liquid Ordinary Oils", labelFr: "Huiles Liquide Oral Ordinaire" },
  { code: "DGJ", labelEn: "Oral Liquid Ordinary Dry Suspensions/Syrups/Drops", labelFr: "Suspensions/Sirops/Gouttes Sèches Liquide Oral Ordinaire" },
  { code: "DGK", labelEn: "Oral Liquid Ordinary Suspensions", labelFr: "Suspensions Liquide Oral Ordinaire" },
  { code: "DGL", labelEn: "Oral Liquid Ordinary Emulsions", labelFr: "Émulsions Liquide Oral Ordinaire" },
  { code: "DGM", labelEn: "Oral Liquid Ordinary Syrups", labelFr: "Sirops Liquide Oral Ordinaire" },
  { code: "DGN", labelEn: "Oral Liquid Ordinary Unit Dose Liquids", labelFr: "Liquides Unidose Liquide Oral Ordinaire" },
  { code: "DGP", labelEn: "Oral Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Liquide Oral Ordinaire" },
  { code: "DGR", labelEn: "Oral Liquid Ordinary Spirits/Wines", labelFr: "Spiritueux/Vins Liquide Oral Ordinaire" },
  { code: "DGY", labelEn: "Oral Liquid Ordinary Other Liquids", labelFr: "Autres Liquides Liquide Oral Ordinaire" },
  { code: "DGZ", labelEn: "Oral Liquid Ordinary Combination Pack Liquids", labelFr: "Pack Combiné de Liquides Liquide Oral Ordinaire" },
  { code: "DH", labelEn: "Oral Liquid Pressurised Aerosols", labelFr: "Aérosols Pressurisés Liquide Oral Ordinaire" },
  { code: "DHP", labelEn: "Oral Liquid Metered-Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Liquide Oral Ordinaire" },
  { code: "DK", labelEn: "Oral Liquid Ordinary Teas", labelFr: "Thés Liquide Oral Ordinaire" },
  { code: "DKA", labelEn: "Oral Liquid Ordinary Drug Teas", labelFr: "Thés Médicaux Liquide Oral Ordinaire" },
  { code: "DKB", labelEn: "Oral Liquid Ordinary Tea Extract Liquids", labelFr: "Extraits de Thé Liquide Oral Ordinaire" },
  { code: "DKJ", labelEn: "Oral Liquid Ordinary Instant Teas", labelFr: "Thés Instantanés Liquide Oral Ordinaire" },
  { code: "DKP", labelEn: "Oral Liquid Ordinary Tea Bags", labelFr: "Sacs de Thé Liquide Oral Ordinaire" },
  { code: "DKV", labelEn: "Oral Liquid Ordinary Tea Tablets", labelFr: "Comprimés de Thé Liquide Oral Ordinaire" },
  { code: "DKY", labelEn: "Oral Liquid Ordinary Other Teas", labelFr: "Autres Thés Liquide Oral Ordinaire" },
  { code: "DY", labelEn: "Oral Liquid Ordinary Other Special Forms", labelFr: "Autres Formes Spéciales Liquide Oral Ordinaire" },
  { code: "DYG", labelEn: "Oral Liquid Food Ready to Eat", labelFr: "Nourriture Prête à Manger Liquide Oral Ordinaire" },
  { code: "DYH", labelEn: "Oral Liquid Food not Ready to Eat", labelFr: "Nourriture Non Prête à Manger Liquide Oral Ordinaire" },
  { code: "E", labelEn: "Oral Liquid Retard", labelFr: "Liquide Oral Retard" },
  { code: "EE", labelEn: "Oral Liquid Retard Powders/Granules", labelFr: "Poudres/Granules Liquide Oral Retard" },
  { code: "EEK", labelEn: "Oral Liquid Retard Soluble Powders", labelFr: "Poudres Solubles Liquide Oral Retard" },
  { code: "EEP", labelEn: "Oral Liquid Retard Unit Dose Powders", labelFr: "Poudres Unidose Liquide Oral Retard" },
  { code: "EG", labelEn: "Oral Liquid Retard Liquids", labelFr: "Liquides Liquide Oral Retard" },
  { code: "EGA", labelEn: "Oral Liquid Retard Liquids", labelFr: "Liquides Liquide Oral Retard" },
  { code: "EGB", labelEn: "Oral Liquid Retard Drops", labelFr: "Gouttes Liquide Oral Retard" },
  { code: "EGM", labelEn: "Oral Liquid Retard Syrups", labelFr: "Sirops Liquide Oral Retard" },
  { code: "F", labelEn: "Parenteral Ordinary", labelFr: "Parenteral Ordinaire" },
  { code: "FM", labelEn: "Parenteral Ordinary Ampoules", labelFr: "Ampoules Parenteral Ordinaire" },
  { code: "FMA", labelEn: "Parenteral Ordinary Ampoules", labelFr: "Ampoules Parenteral Ordinaire" },
  { code: "FMB", labelEn: "Parenteral Ordinary Dry Ampoules", labelFr: "Ampoules Sèches Parenteral Ordinaire" },
  { code: "FMC", labelEn: "Parenteral Ordinary I V Ampoules", labelFr: "Ampoules I V Parenteral Ordinaire" },
  { code: "FMD", labelEn: "Parenteral Ordinary I M Ampoules", labelFr: "Ampoules I M Parenteral Ordinaire" },
  { code: "FME", labelEn: "Parenteral Ordinary S C Ampoules", labelFr: "Ampoules S C Parenteral Ordinaire" },
  { code: "FMF", labelEn: "Parenteral Ordinary Intradermal Ampoules", labelFr: "Ampoules Intradermiques Parenteral Ordinaire" },
  { code: "FMY", labelEn: "Parenteral Ordinary Other Ampoules", labelFr: "Autres Ampoules Parenteral Ordinaire" },
  { code: "FMZ", labelEn: "Parenteral Ordinary Combination Pack Ampoules", labelFr: "Pack Combiné d'Ampoules Parenteral Ordinaire" },
  { code: "FN", labelEn: "Parenteral Ordinary Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNA", labelEn: "Parenteral Ordinary Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNB", labelEn: "Parenteral Ordinary Dry Pre-Filled Syringes", labelFr: "Seringues Sèches Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNC", labelEn: "Parenteral Ordinary I V Pre-Filled Syringes", labelFr: "Seringues I V Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FND", labelEn: "Parenteral Ordinary I M Pre-Filled Syringes", labelFr: "Seringues I M Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNE", labelEn: "Parenteral Ordinary S C Pre-Filled Syringes", labelFr: "Seringues S C Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNF", labelEn: "Parenteral Ordinary Intradermal Pre-filled Syringes", labelFr: "Seringues Intradermiques Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNH", labelEn: "Parenteral Ordinary Pre-Filled Autoinjectors", labelFr: "Auto-injecteurs Prêts à l'Emploi Parenteral Ordinaire" },
  { code: "FNY", labelEn: "Parenteral Ordinary Other Pre-Filled Syringes", labelFr: "Autres Seringues Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FNZ", labelEn: "Parenteral Ordinary Combination Pack Pre-Filled Syringes", labelFr: "Pack Combiné de Seringues Prêtes à l'Emploi Parenteral Ordinaire" },
  { code: "FP", labelEn: "Parenteral Ordinary Vials", labelFr: "Flacons Parenteral Ordinaire" },
  { code: "FPA", labelEn: "Parenteral Ordinary Vials", labelFr: "Flacons Parenteral Ordinaire" },
  { code: "FPB", labelEn: "Parenteral Ordinary Dry Vials", labelFr: "Flacons Sèches Parenteral Ordinaire" },
  { code: "FPC", labelEn: "Parenteral Ordinary I V Vials", labelFr: "Flacons I V Parenteral Ordinaire" },
  { code: "FPD", labelEn: "Parenteral Ordinary I M Vials", labelFr: "Flacons I M Parenteral Ordinaire" },
  { code: "FPE", labelEn: "Parenteral Ordinary S C Vials", labelFr: "Flacons S C Parenteral Ordinaire" },
  { code: "FPF", labelEn: "Parenteral Ordinary Intradermal Vials", labelFr: "Flacons Intradermiques Parenteral Ordinaire" },
  { code: "FPY", labelEn: "Parenteral Ordinary Other Vials", labelFr: "Autres Flacons Parenteral Ordinaire" },
  { code: "FPZ", labelEn: "Parenteral Ordinary Combination Pack Vials", labelFr: "Pack Combiné de Flacons Parenteral Ordinaire" },
  { code: "FQ", labelEn: "Parenteral Ordinary Infusions", labelFr: "Perfusions Parenteral Ordinaire" },
  { code: "FQA", labelEn: "Parenteral Ordinary Infusion Ampoules", labelFr: "Ampoules de Perfusion Parenteral Ordinaire" },
  { code: "FQB", labelEn: "Parenteral Ordinary Infusion Dry Ampoules", labelFr: "Ampoules Sèches de Perfusion Parenteral Ordinaire" },
  { code: "FQC", labelEn: "", labelFr: "Flacons/Bouteilles de Perfusion Parenteral Ordinaire" },
  { code: "FQD", labelEn: "Parenteral Ordinary Infusion Dry Vials/Bottles", labelFr: "Flacons/Bouteilles Sèches de Perfusion Parenteral Ordinaire" },
  { code: "FQE", labelEn: "Parenteral Ordinary Infusion Bags", labelFr: "Sacs de Perfusion Parenteral Ordinaire" },
  { code: "FQF", labelEn: "Parenteral Ordinary Infusion Cartridges", labelFr: "Cartouches de Perfusion Parenteral Ordinaire" },
  { code: "FQY", labelEn: "Parenteral Ordinary Other Infusions", labelFr: "Autres Perfusions Parenteral Ordinaire" },
  { code: "FR", labelEn: "Parenteral Ordinary Cartridges/Pens", labelFr: "Cartouches/Stylos Parenteral Ordinaire" },
  { code: "FRA", labelEn: "Parenteral Ordinary Cartridges", labelFr: "Cartouches Parenteral Ordinaire" },
  { code: "FRB", labelEn: "Parenteral Ordinary Dry Cartridges", labelFr: "Cartouches Sèches Parenteral Ordinaire" },
  { code: "FRF", labelEn: "Parenteral Ordinary Pre-Filled Pens", labelFr: "Stylos Prêts à l'Emploi Parenteral Ordinaire" },
  { code: "FRG", labelEn: "Parenteral Ordinary Dry Pre-Filled Pens", labelFr: "Stylos Sèches Prêts à l'Emploi Parenteral Ordinaire" },
  { code: "FRP", labelEn: "Parenteral Ordinary Unit Dose Cartridges", labelFr: "Cartouches Unidose Parenteral Ordinaire" },
  { code: "G", labelEn: "Parenteral Retard", labelFr: "Parenteral Retard" },
  { code: "GM", labelEn: "Parenteral Retard Ampoules", labelFr: "Ampoules Parenteral Retard" },
  { code: "GMA", labelEn: "Parenteral Retard Ampoules", labelFr: "Ampoules Parenteral Retard" },
  { code: "GMB", labelEn: "Parenteral Retard Dry Ampoules", labelFr: "Ampoules Sèches Parenteral Retard" },
  { code: "GMD", labelEn: "Parenteral Retard I M Ampoules", labelFr: "Ampoules I M Parenteral Retard" },
  { code: "GME", labelEn: "Parenteral Retard S C Ampoules", labelFr: "Ampoules S C Parenteral Retard" },
  { code: "GMY", labelEn: "Parenteral Retard Other Ampoules", labelFr: "Autres Ampoules Parenteral Retard" },
  { code: "GN", labelEn: "Parenteral Retard Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Parenteral Retard" },
  { code: "GNA", labelEn: "Parenteral Retard Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Parenteral Retard" },
  { code: "GNB", labelEn: "Parenteral Retard Dry Pre-Filled Syringes", labelFr: "Seringues Sèches Prêtes à l'Emploi Parenteral Retard" },
  { code: "GND", labelEn: "Parenteral Retard I M Pre-Filled Syringes", labelFr: "Seringues I M Prêtes à l'Emploi Parenteral Retard" },
  { code: "GNE", labelEn: "Parenteral Retard S C Pre-Filled Syringes", labelFr: "Seringues S C Prêtes à l'Emploi Parenteral Retard" },
  { code: "GNH", labelEn: "Parenteral Retard Pre-Filled Autoinjectors", labelFr: "Auto-injecteurs Prêts à l'Emploi Parenteral Retard" },
  { code: "GNY", labelEn: "Parenteral Retard Other Pre-Filled Syringes", labelFr: "Autres Seringues Prêtes à l'Emploi Parenteral Retard" },
  { code: "GP", labelEn: "Parenteral Retard Vials", labelFr: "Flacons Parenteral Retard" },
  { code: "GPA", labelEn: "Parenteral Retard Vials", labelFr: "Flacons Parenteral Retard" },
  { code: "GPB", labelEn: "Parenteral Retard Dry Vials", labelFr: "Flacons Sèches Parenteral Retard" },
  { code: "GPD", labelEn: "Parenteral Retard I M Vials", labelFr: "Flacons I M Parenteral Retard" },
  { code: "GPE", labelEn: "Parenteral Retard S C Vials", labelFr: "Flacons S C Parenteral Retard" },
  { code: "GPY", labelEn: "Parenteral Retard Other Vials", labelFr: "Autres Flacons Parenteral Retard" },
  { code: "GR", labelEn: "Parenteral Retard Cartridges/Pens", labelFr: "Cartouches/Stylos Parenteral Retard" },
  { code: "GRA", labelEn: "Parenteral Retard Cartridges", labelFr: "Cartouches Parenteral Retard" },
  { code: "GRF", labelEn: "Parenteral Retard Pre-Filled Pens", labelFr: "Stylos Prêts à l'Emploi Parenteral Retard" },
  { code: "GRG", labelEn: "Parenteral Retard Dry Pre-Filled Pens", labelFr: "Stylos Sèches Prêts à l'Emploi Parenteral Retard" },
  { code: "GRP", labelEn: "Parenteral Retard Unit Dose Cartridges", labelFr: "Cartouches Unidose Parenteral Retard" },
  { code: "GY", labelEn: "Parenteral Retard Other Special Forms", labelFr: "Autres Formes Spéciales Parenteral Retard" },
  { code: "GYV", labelEn: "Parenteral Retard Implants", labelFr: "Implants Parenteral Retard" },
  { code: "H", labelEn: "Rectal Systemic", labelFr: "Rectal Systémique" },
  { code: "HA", labelEn: "Rectal Systemic Tablets", labelFr: "Comprimés Rectal Systémique" },
  { code: "HAX", labelEn: "Rectal Systemic Enema Tablets", labelFr: "Comprimés à Lavement Rectal Systémique" },
  { code: "HC", labelEn: "Rectal Systemic Capsules", labelFr: "Capsules Rectal Systémique" },
  { code: "HCA", labelEn: "Rectal Systemic Capsules", labelFr: "Capsules Rectal Systémique" },
  { code: "HE", labelEn: "Rectal Systemic Powders/Granules", labelFr: "Poudres/Granules Rectal Systémique" },
  { code: "HEK", labelEn: "Rectal Systemic Soluble Powder", labelFr: "Poudres Solubles Rectal Systémique" },
  { code: "HEX", labelEn: "Rectal Systemic Enema Powder", labelFr: "Poudres à Lavement Rectal Systémique" },
  { code: "HG", labelEn: "Rectal Systemic Liquids", labelFr: "Liquides Rectal Systémique" },
  { code: "HGX", labelEn: "Rectal Systemic Enema Liquids", labelFr: "Liquides à Lavement Rectal Systémique" },
  { code: "HH", labelEn: "Rectal Systemic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Rectal Systémique" },
  { code: "HHP", labelEn: "Rectal Systemic Metered-Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Rectal Systémique" },
  { code: "HHT", labelEn: "Rectal Systemic Pressurised Foams", labelFr: "Mousses Pressurisées Rectal Systémique" },
  { code: "HL", labelEn: "Rectal Systemic Suppositories", labelFr: "Suppositoires Rectal Systémique" },
  { code: "HLA", labelEn: "Rectal Systemic Suppositories", labelFr: "Suppositoires Rectal Systémique" },
  { code: "HLB", labelEn: "Rectal Systemic Adult Suppositories", labelFr: "Suppositoires Adultes Rectal Systémique" },
  { code: "HLC", labelEn: "Rectal Systemic Paediatric Suppositories", labelFr: "Suppositoires Pédiatriques Rectal Systémique" },
  { code: "HLX", labelEn: "Rectal Systemic Micro-Enemas", labelFr: "Micro-Lavements Rectal Systémique" },
  { code: "HLY", labelEn: "Rectal Systemic Other Suppositories", labelFr: "Autres Suppositoires Rectal Systémique" },
  { code: "HS", labelEn: "Rectal Systemic Ointments", labelFr: "Onguent Rectal Systémique" },
  { code: "HSN", labelEn: "Rectal Systemic Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Rectal Systémique" },
  { code: "HV", labelEn: "Rectal Systemic Gels and Sols", labelFr: "Gels et Solutions Rectal Systémique" },
  { code: "HVA", labelEn: "Rectal Systemic Gels and Sols", labelFr: "Gels et Solutions Rectal Systémique" },
  { code: "I", labelEn: "Nasal Systemic", labelFr: "Nasal Systémique" },
  { code: "IE", labelEn: "Nasal Systemic Powders/Granules", labelFr: "Poudres/Granules Nasal Systémique" },
  { code: "IEP", labelEn: "Nasal Systemic Unit Dose Powders", labelFr: "Poudres Unidose Nasal Systémique" },
  { code: "IG", labelEn: "Nasal Systemic Liquids", labelFr: "Liquides Nasal Systémique" },
  { code: "IGB", labelEn: "Nasal Systemic Drops", labelFr: "Gouttes Nasal Systémique" },
  { code: "IGJ", labelEn: "Nasal Systemic Dry Suspensions/Syrups/Drops", labelFr: "Suspensions/Sirops/Gouttes Sèches Nasal Systémique" },
  { code: "IGN", labelEn: "Nasal Systemic Unit Dose Liquids", labelFr: "Liquides Unidose Nasal Systémique" },
  { code: "IGP", labelEn: "Nasal Systemic Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Nasal Systémique" },
  { code: "IH", labelEn: "Nasal Systemic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Nasal Systémique" },
  { code: "IHP", labelEn: "Nasal Systemic Metered Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Nasal Systémique" },
  { code: "IS", labelEn: "Nasal Systemic Ointments", labelFr: "Onguent Nasal Systémique" },
  { code: "ISA", labelEn: "Nasal Systemic Ointments", labelFr: "Onguent Nasal Systémique" },
  { code: "IV", labelEn: "Nasal Systemic Gels and Sols", labelFr: "Gels et Solutions Nasal Systémique" },
  { code: "IVN", labelEn: "Nasal Systemic Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Nasal Systémique" },
  { code: "IVP", labelEn: "Nasal Systemic Metered-Dose Gels/Sols", labelFr: "Gels/Solutions Dose Mesurée Nasal Systémique" },
  { code: "J", labelEn: "Other Systemic", labelFr: "Autre Systémique" },
  { code: "JC", labelEn: "Other Systemic Capsules", labelFr: "Capsules Autre Systémique" },
  { code: "JCT", labelEn: "Other Systemic Inhaler Capsules", labelFr: "Capsules d'Inhalation Autre Systémique" },
  { code: "JCV", labelEn: "Other Systemic Capsules for Topical Application", labelFr: "Capsules pour Application Topique Autre Systémique" },
  { code: "JD", labelEn: "Other Systemic Solid Special Forms", labelFr: "Formes Solides Spéciales Autre Systémique" },
  { code: "JDY", labelEn: "Other Systemic Special Solids", labelFr: "Autres Formes Solides Spéciales Autre Systémique" },
  { code: "JE", labelEn: "Other Systemic Powders/Granules", labelFr: "Poudres/Granules Autre Systémique" },
  { code: "JEA", labelEn: "Other Systemic Powder", labelFr: "Poudre Autre Systémique" },
  { code: "JEN", labelEn: "Other Systemic Unit Dose Powder Inhaler Refillable", labelFr: "Poudre d'Inhalation Refillable Unidose Autre Systémique" },
  { code: "JEY", labelEn: "Other Systemic Other Powders/Granules", labelFr: "Autres Poudres/Granules Autre Systémique" },
  { code: "JF", labelEn: "Other Systemic Gases", labelFr: "Gaz Autre Systémique" },
  { code: "JFA", labelEn: "Other Systemic Gases for Inhalation", labelFr: "Gaz pour Inhalation Autre Systémique" },
  { code: "JG", labelEn: "Other Systemic Liquids", labelFr: "Liquides Autre Systémique" },
  { code: "JGA", labelEn: "Other Systemic Liquids", labelFr: "Liquides Autre Systémique" },
  { code: "JGB", labelEn: "Other Systemic Drops", labelFr: "Gouttes Autre Systémique" },
  { code: "JGC", labelEn: "Other Systemic Sprays without Gas", labelFr: "Sprays Sans Gaz Autre Systémique" },
  { code: "JGE", labelEn: "Other Systemic Liquid Inhalations", labelFr: "Inhalations Liquides Autre Systémique" },
  { code: "JGH", labelEn: "Other Systemic Oils", labelFr: "Huiles Autre Systémique" },
  { code: "JGN", labelEn: "Other Systemic Unit Dose Liquids", labelFr: "Liquides Unidose Autre Systémique" },
  { code: "JGP", labelEn: "Other Systemic Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Autre Systémique" },
  { code: "JGY", labelEn: "Other Systemic Other Liquids", labelFr: "Autres Liquides Autre Systémique" },
  { code: "JH", labelEn: "Other Systemic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Autre Systémique" },
  { code: "JHA", labelEn: "Other Systemic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Autre Systémique" },
  { code: "JHP", labelEn: "Other Systemic Metered-Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Autre Systémique" },
  { code: "JHT", labelEn: "Other Systemic Pressurised Foams", labelFr: "Mousses Pressurisées Autre Systémique" },
  { code: "JR", labelEn: "Other Systemic Cartridges/Pens", labelFr: "Cartouches/Stylos Autre Systémique" },
  { code: "JRP", labelEn: "Other Systemic Unit Dose Cartridges", labelFr: "Cartouches Unidose Autre Systémique" },
  { code: "JS", labelEn: "Other Systemic Ointments", labelFr: "Onguent Autre Systémique" },
  { code: "JSA", labelEn: "Other Systemic Ointments", labelFr: "Onguent Autre Systémique" },
  { code: "JSN", labelEn: "Other Systemic Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Autre Systémique" },
  { code: "JT", labelEn: "Other Systemic Creams", labelFr: "Crèmes Autre Systémique" },
  { code: "JTA", labelEn: "Other Systemic Creams", labelFr: "Crèmes Autre Systémique" },
  { code: "JTN", labelEn: "Other Systemic Unit Dose Creams", labelFr: "Crèmes Unidose Autre Systémique" },
  { code: "JV", labelEn: "Other Systemic Gels and Sols", labelFr: "Gels et Solutions Autre Systémique" },
  { code: "JVA", labelEn: "Other Systemic Gels and Sols", labelFr: "Gels et Solutions Autre Systémique" },
  { code: "JVN", labelEn: "Other Systemic Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Autre Systémique" },
  { code: "JVP", labelEn: "Other Systemic Metered-Dose Gels/Sols", labelFr: "Gels/Solutions Dose Mesurée Autre Systémique" },
  { code: "JW", labelEn: "Other Systemic Medicated Dressings", labelFr: "Pansements Médicamentés Autre Systémique" },
  { code: "JWM", labelEn: "Other Systemic Transdermal Systems", labelFr: "Systèmes Transdermiques Autre Systémique" },
  { code: "JWN", labelEn: "Other Systemic Transdermal Patches", labelFr: "Patchs Transdermiques Autre Systémique" },
  { code: "JY", labelEn: "Other Systemic Other Special Forms", labelFr: "Autres Formes Spéciales Autre Systémique" },
  { code: "JYM", labelEn: "Other Systemic Stick and Roll-Ons", labelFr: "Sticks et Roll-Ons Autre Systémique" },
  { code: "K", labelEn: "Oral Topical", labelFr: "Topique Oral" },
  { code: "KA", labelEn: "Oral Topical Tablets", labelFr: "Comprimés Topique Oral" },
  { code: "KAE", labelEn: "Oral Topical Buccal Tablets", labelFr: "Comprimés Buccaux Topique Oral" },
  { code: "KAF", labelEn: "Oral Topical Sublingual Tablets", labelFr: "Comprimés Sublinguaux Topique Oral" },
  { code: "KAG", labelEn: "Oral Topical Chewable Tablets", labelFr: "Comprimés à Croquer Topique Oral" },
  { code: "KAH", labelEn: "Oral Topical Effervescent Tablets", labelFr: "Comprimés Effervescents Topique Oral" },
  { code: "KAK", labelEn: "Oral Topical Soluble Tablets", labelFr: "Comprimés Solubles Topique Oral" },
  { code: "KAZ", labelEn: "Oral Topical Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Topique Oral" },
  { code: "KC", labelEn: "Oral Topical Capsules", labelFr: "Capsules Topique Oral" },
  { code: "KCA", labelEn: "Oral Topical Capsules", labelFr: "Capsules Topique Oral" },
  { code: "KD", labelEn: "Oral Topical Forms", labelFr: "Formes Spéciales Topique Oral" },
  { code: "KDD", labelEn: "Oral Topical Pellets", labelFr: "Granules Topique Oral" },
  { code: "KDE", labelEn: "Oral Topical Lozenges", labelFr: "Pastilles Topique Oral" },
  { code: "KDF", labelEn: "Oral Topical Chewing Gum", labelFr: "Gomme à Mâcher Topique Oral" },
  { code: "KDG", labelEn: "Oral Topical Sweets/Candy/Bonbons", labelFr: "Bonbons/Sucreries Topique Oral" },
  { code: "KDY", labelEn: "Oral Topical Other Special Forms", labelFr: "Autres Formes Spéciales Topique Oral" },
  { code: "KE", labelEn: "Oral Topical Powder/Granules", labelFr: "Poudres/Granules Topique Oral" },
  { code: "KEA", labelEn: "Oral Topical Powders", labelFr: "Poudres Topique Oral" },
  { code: "KEB", labelEn: "Oral Topical Granules", labelFr: "Granules Topique Oral" },
  { code: "KEK", labelEn: "Oral Topical Soluble Powders", labelFr: "Poudres Solubles Topique Oral" },
  { code: "KEP", labelEn: "Oral Topical Unit Dose Powders", labelFr: "Poudres Unidose Topique Oral" },
  { code: "KEZ", labelEn: "Oral Topical Combination Pack/Powder/Granules", labelFr: "Pack Combiné de Poudres/Granules Topique Oral" },
  { code: "KG", labelEn: "Oral Topical Liquids", labelFr: "Liquides Topique Oral" },
  { code: "KGA", labelEn: "Oral Topical Liquids", labelFr: "Liquides Topique Oral" },
  { code: "KGB", labelEn: "Oral Topical Drops", labelFr: "Gouttes Topique Oral" },
  { code: "KGC", labelEn: "Oral Topical Sprays without Gas", labelFr: "Sprays Sans Gaz Topique Oral" },
  { code: "KGD", labelEn: "Oral Topical Collodion/Lacquers", labelFr: "Collodion/Lacquers Topique Oral" },
  { code: "KGH", labelEn: "Oral Topical Oils", labelFr: "Huiles Topique Oral" },
  { code: "KGJ", labelEn: "Oral Topical Dry Suspensions/Syrups/Drops", labelFr: "Suspensions/Sirops/Gouttes Sèches Topique Oral" },
  { code: "KGK", labelEn: "Oral Topical Suspensions", labelFr: "Suspensions Topique Oral" },
  { code: "KGL", labelEn: "Oral Topical Emulsions", labelFr: "Émulsions Topique Oral" },
  { code: "KGN", labelEn: "Oral Topical Unit Dose Liquids", labelFr: "Liquides Unidose Topique Oral" },
  { code: "KGP", labelEn: "Oral Topical Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Topique Oral" },
  { code: "KGS", labelEn: "Oral Topical Lotions", labelFr: "Lotions Topique Oral" },
  { code: "KH", labelEn: "Oral Topical Pressurised Aerosols", labelFr: "Aérosols Pressurisés Topique Oral" },
  { code: "KHA", labelEn: "Oral Topical Pressurised Aerosols", labelFr: "Aérosols Pressurisés Topique Oral" },
  { code: "KHP", labelEn: "Oral Topical Metered-Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Topique Oral" },
  { code: "KS", labelEn: "Oral Topical Ointments", labelFr: "Onguent Topique Oral" },
  { code: "KSA", labelEn: "Oral Topical Ointments", labelFr: "Onguent Topique Oral" },
  { code: "KSB", labelEn: "Oral Topical Pastes", labelFr: "Pâte Topique Oral" },
  { code: "KSZ", labelEn: "Oral Topical Combination Pack Ointments", labelFr: "Pack Combiné d'Onguent Topique Oral" },
  { code: "KT", labelEn: "Oral Topical Creams", labelFr: "Crèmes Topique Oral" },
  { code: "KTA", labelEn: "Oral Topical Creams", labelFr: "Crèmes Topique Oral" },
  { code: "KTZ", labelEn: "Oral Topical Combination Pack Creams", labelFr: "Pack Combiné de Crèmes Topique Oral" },
  { code: "KV", labelEn: "Oral Topical Gels and Sols", labelFr: "Gels et Solutions Topique Oral" },
  { code: "KVA", labelEn: "Oral Topical Gels and Sols", labelFr: "Gels et Solutions Topique Oral" },
  { code: "KVN", labelEn: "Oral Topical Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Topique Oral" },
  { code: "KW", labelEn: "Oral Topical Medicated Dressings", labelFr: "Pansements Médicamentés Topique Oral" },
  { code: "KWE", labelEn: "Oral Topical Tampons with Substance", labelFr: "Tampons avec Substance Topique Oral" },
  { code: "KWH", labelEn: "Oral Topical Sponges with Substance", labelFr: "Éponges avec Substance Topique Oral" },
  { code: "KWY", labelEn: "Oral Topical Other Medicated Dressings", labelFr: "Autres Pansements Médicamentés Topique Oral" },
  { code: "KY", labelEn: "Oral Topical Other Special Forms", labelFr: "Autres Formes Spéciales Topique Oral" },
  { code: "KYK", labelEn: "Oral Topical Styli and Wound Cones Non-Rectal", labelFr: "Styli et Cones de Plaies Non-Rectal Topique Oral" },
  { code: "KYM", labelEn: "Oral Topical Sticks and Roll-Ons", labelFr: "Sticks et Roll-Ons Topique Oral" },
  { code: "KZ", labelEn: "Oral Topical Medical Aids", labelFr: "Aides Médicales Topique Oral" },
  { code: "KZE", labelEn: "Oral Topical Tampons without Substance", labelFr: "Tampons sans Substance Topique Oral" },
  { code: "KZH", labelEn: "Oral Topical Sponges without Substance", labelFr: "Éponges sans Substance Topique Oral" },
  { code: "KZJ", labelEn: "Oral Topical Tissue Absorbable Medical Aids", labelFr: "Tissus Absorbables Aides Médicales Topique Oral" },
  { code: "KZV", labelEn: "Oral Topical Diagnostic Tests Excluding Sticks", labelFr: "Tests de Diagnostic Excluant les Styli Topique Oral" },
  { code: "KZY", labelEn: "Oral Topical Other Medical Aids", labelFr: "Autres Aides Médicales Topique Oral" },
  { code: "M", labelEn: "Topical Dermatological, Haemorrhoidal, External", labelFr: "Dermatologique, Hémorroïdaire, Externe Topique" },
  { code: "MA", labelEn: "Topical External Tablets", labelFr: "Comprimés Externe Topique" },
  { code: "MAA", labelEn: "Topical External Tablets", labelFr: "Comprimés Externe Topique" },
  { code: "MAH", labelEn: "Topical External Effervescent Tablets", labelFr: "Comprimés Effervescents Externe Topique" },
  { code: "MAK", labelEn: "Topical External Soluble Tablets", labelFr: "Comprimés Solubles Externe Topique" },
  { code: "MAZ", labelEn: "Topical External Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Externe Topique" },
  { code: "MC", labelEn: "Topical External Capsules", labelFr: "Capsules Externe Topique" },
  { code: "MCV", labelEn: "Topical External Capsules", labelFr: "Capsules Externe Topique" },
  { code: "MD", labelEn: "Topical External Solid Special Forms", labelFr: "Formes Solides Spéciales Externe Topique" },
  { code: "MDY", labelEn: "Topical External Other Special Solid Forms", labelFr: "Autres Formes Solides Spéciales Externe Topique" },
  { code: "ME", labelEn: "Topical External Powders/Granules", labelFr: "Poudres/Granules Externe Topique" },
  { code: "MEA", labelEn: "Topical External Powders", labelFr: "Poudres Externe Topique" },
  { code: "MEB", labelEn: "Topical External Granules", labelFr: "Granules Externe Topique" },
  { code: "MEC", labelEn: "Topical External Dusting Powders", labelFr: "Poudres de Saupoudrage Externe Topique" },
  { code: "MEK", labelEn: "Topical External Soluble Powders", labelFr: "Poudres Solubles Externe Topique" },
  { code: "MEP", labelEn: "Topical External Unit Dose Powders", labelFr: "Poudres Unidose Externe Topique" },
  { code: "MEX", labelEn: "Topical External Enema Powders", labelFr: "Poudres à Lavement Externe Topique" },
  { code: "MEY", labelEn: "Topical External Other Powders/Granules", labelFr: "Autres Poudres/Granules Externe Topique" },
  { code: "MEZ", labelEn: "Topical External Combination Pack Powders/Granules", labelFr: "Pack Combiné de Poudres/Granules Externe Topique" },
  { code: "MG", labelEn: "Topical External Liquids", labelFr: "Liquides Externe Topique" },
  { code: "MGA", labelEn: "Topical External Liquids", labelFr: "Liquides Externe Topique" },
  { code: "MGB", labelEn: "Topical External Drops", labelFr: "Gouttes Externe Topique" },
  { code: "MGC", labelEn: "Topical External Sprays without Gas", labelFr: "Sprays Sans Gaz Externe Topique" },
  { code: "MGD", labelEn: "Topical External Collodion/Lacquers", labelFr: "Collodion/Lacquers Externe Topique" },
  { code: "MGE", labelEn: "Topical External Liquid Inhalations", labelFr: "Inhalations Liquides Externe Topique" },
  { code: "MGH", labelEn: "Topical External Oils", labelFr: "Huiles Externe Topique" },
  { code: "MGJ", labelEn: "Topical External Dry Suspensions/Syrups/Drops", labelFr: "Suspensions/Sirops/Gouttes Sèches Externe Topique" },
  { code: "MGK", labelEn: "Topical External Suspensions", labelFr: "Suspensions Externe Topique" },
  { code: "MGL", labelEn: "Topical External Emulsions", labelFr: "Émulsions Externe Topique" },
  { code: "MGN", labelEn: "Topical External Unit Dose Liquids", labelFr: "Liquides Unidose Externe Topique" },
  { code: "MGP", labelEn: "Topical External Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Externe Topique" },
  { code: "MGR", labelEn: "Topical External Spirits", labelFr: "Spiritueux Externe Topique" },
  { code: "MGS", labelEn: "Topical External Lotions", labelFr: "Lotions Externe Topique" },
  { code: "MGT", labelEn: "Topical Dermatological Shaking Mixtures", labelFr: "Mélanges à Secouer Dermatologiques Externe Topique" },
  { code: "MGW", labelEn: "Topical External Liquid Soaps/Washes", labelFr: "Savons/Lavages Liquides Externe Topique" },
  { code: "MGX", labelEn: "Topical External Enema Liquids", labelFr: "Lavements Liquides Externe Topique" },
  { code: "MGZ", labelEn: "Topical External Combination Pack Liquids", labelFr: "Pack Combiné de Liquides Externe Topique" },
  { code: "MH", labelEn: "Topical External Pressurised Aerosols", labelFr: "Aérosols Pressurisés Externe Topique" },
  { code: "MHA", labelEn: "Topical External Pressurised Aerosols", labelFr: "Aérosols Pressurisés Externe Topique" },
  { code: "MHC", labelEn: "Topical External Pressurised Powders", labelFr: "Poudres Pressurisées Externe Topique" },
  { code: "MHP", labelEn: "Topical External Metered-Dose Pressurised Aerosols", labelFr: "Aérosols Pressurisés Dose Mesurée Externe Topique" },
  { code: "MHS", labelEn: "Topical External Pressurised Ointments and Creams", labelFr: "Onguent et Crèmes Pressurisés Externe Topique" },
  { code: "MHT", labelEn: "Topical External Pressurised Foams", labelFr: "Mousses Pressurisées Externe Topique" },
  { code: "MHW", labelEn: "Topical External Pressurised Soaps/Washes", labelFr: "Savons/Lavages Pressurisés Externe Topique" },
  { code: "MHY", labelEn: "Topical External Other Pressurised Aerosols", labelFr: "Autres Aérosols Pressurisés Externe Topique" },
  { code: "MHZ", labelEn: "Topical External Combination Pack Pressurised Aerosols", labelFr: "Pack Combiné d'Aérosols Pressurisés Externe Topique" },
  { code: "MJ", labelEn: "Topical External Bath Preparations", labelFr: "Préparations de Bain Externe Topique" },
  { code: "MJA", labelEn: "Topical External Bath Preparations", labelFr: "Préparations de Bain Externe Topique" },
  { code: "MJB", labelEn: "Topical External Solid Substances for Baths", labelFr: "Substances Solides pour Bains Externe Topique" },
  { code: "MJH", labelEn: "Topical External Bath Oils", labelFr: "Huiles de Bain Externe Topique" },
  { code: "MJL", labelEn: "Topical External Bath Emulsions", labelFr: "Émulsions de Bain Externe Topique" },
  { code: "MJP", labelEn: "Topical External Partial Baths", labelFr: "Bains Partiels Externe Topique" },
  { code: "MJS", labelEn: "Topical External Foot Baths", labelFr: "Bains de Pied Externe Topique" },
  { code: "MJT", labelEn: "Topical External Foam Baths", labelFr: "Mousses de Bain Externe Topique" },
  { code: "MJV", labelEn: "Topical External Bath Tablets", labelFr: "Comprimés de Bain Externe Topique" },
  { code: "MJY", labelEn: "Topical External Other Baths", labelFr: "Autres Bains Externe Topique" },
  { code: "MJZ", labelEn: "Topical External Combination Pack Baths", labelFr: "Pack Combiné de Bains Externe Topique" },
  { code: "ML", labelEn: "Topical External Suppositories", labelFr: "Suppositoires Externe Topique" },
  { code: "MLA", labelEn: "Topical External Suppositories", labelFr: "Suppositoires Externe Topique" },
  { code: "MLB", labelEn: "Topical External Adult Suppositories", labelFr: "Suppositoires Adultes Externe Topique" },
  { code: "MLC", labelEn: "Topical External Paediatric Suppositories", labelFr: "Suppositoires Pédiatriques Externe Topique" },
  { code: "MLX", labelEn: "Topical External Micro-Enemas", labelFr: "Micro-Lavements Externe Topique" },
  { code: "MLY", labelEn: "Topical External Other Suppositories", labelFr: "Autres Suppositoires Externe Topique" },
  { code: "MLZ", labelEn: "Topical External Combination Pack Suppositories", labelFr: "Pack Combiné de Suppositoires Externe Topique" },
  { code: "MM", labelEn: "Topical External Ampoules", labelFr: "Ampoules Externe Topique" },
  { code: "MMA", labelEn: "Topical External Ampoules", labelFr: "Ampoules Externe Topique" },
  { code: "MMB", labelEn: "Topical External Dry Ampoules", labelFr: "Ampoules Sèches Externe Topique" },
  { code: "MMF", labelEn: "Topical External Intradermal Ampoules", labelFr: "Ampoules Intradermiques Externe Topique" },
  { code: "MMS", labelEn: "Topical External Instillation Ampoules", labelFr: "Ampoules d'Instillation Externe Topique" },
  { code: "MMY", labelEn: "Topical External Other Ampoules", labelFr: "Autres Ampoules Externe Topique" },
  { code: "MN", labelEn: "Topical External Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Externe Topique" },
  { code: "MNA", labelEn: "Topical External Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Externe Topique" },
  { code: "MNF", labelEn: "Topical External Intradermal Pre-filled Syringes", labelFr: "Seringues Intradermiques Prêtes à l'Emploi Externe Topique" },
  { code: "MNS", labelEn: "Topical External Instillation Pre-Filled Syringes", labelFr: "Seringues d'Instillation Prêtes à l'Emploi Externe Topique" },
  { code: "MNY", labelEn: "Topical External Other Pre-Filled Syringes", labelFr: "Autres Seringues Prêtes à l'Emploi Externe Topique" },
  { code: "MP", labelEn: "Topical External Vials", labelFr: "Flacons Externe Topique" },
  { code: "MPA", labelEn: "Topical External Vials", labelFr: "Flacons Externe Topique" },
  { code: "MPB", labelEn: "Topical External Dry Vials", labelFr: "Flacons Sèches Externe Topique" },
  { code: "MPF", labelEn: "Topical External Intradermal Vials", labelFr: "Flacons Intradermiques Externe Topique" },
  { code: "MPS", labelEn: "Topical External Instillation Vials", labelFr: "Flacons d'Instillation Externe Topique" },
  { code: "MPY", labelEn: "Topical External Other Vials", labelFr: "Autres Flacons Externe Topique" },
  { code: "MQ", labelEn: "Topical External Infusions", labelFr: "Perfusions Externe Topique" },
  { code: "MQS", labelEn: "Dialysis Irrigation Perfusion Solutions", labelFr: "Solutions de Dialyse/Irrigation/Perfusion Externe Topique" },
  { code: "MS", labelEn: "Topical External Ointments", labelFr: "Onguent Externe Topique" },
  { code: "MSA", labelEn: "Topical External Ointments", labelFr: "Onguent Externe Topique" },
  { code: "MSB", labelEn: "Topical External Pastes", labelFr: "Pâte Externe Topique" },
  { code: "MSL", labelEn: "Topical External Emulsion Ointments", labelFr: "Onguent d'Émulsion Externe Topique" },
  { code: "MSN", labelEn: "Topical External Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Externe Topique" },
  { code: "MSW", labelEn: "Topical External Soap Pastes", labelFr: "Pâtes de Savon Externe Topique" },
  { code: "MSY", labelEn: "Topical External Other Ointments", labelFr: "Autres Onguent Externe Topique" },
  { code: "MSZ", labelEn: "Topical External Combination Pack Ointments", labelFr: "Pack Combiné d'Onguent Externe Topique" },
  { code: "MT", labelEn: "Topical External Creams", labelFr: "Crèmes Externe Topique" },
  { code: "MTA", labelEn: "Topical External Creams", labelFr: "Crèmes Externe Topique" },
  { code: "MTL", labelEn: "Topical External Emulsion Creams", labelFr: "Crèmes d'Émulsion Externe Topique" },
  { code: "MTN", labelEn: "Topical External Unit Dose Creams", labelFr: "Crèmes Unidose Externe Topique" },
  { code: "MTP", labelEn: "Topical External Metered-Dose Creams", labelFr: "Crèmes Dose Mesurée Externe Topique" },
  { code: "MTW", labelEn: "Topical External Cream Soaps/Washes", labelFr: "Savons/Lavages de Crème Externe Topique" },
  { code: "MTY", labelEn: "Topical External Other Creams", labelFr: "Autres Crèmes Externe Topique" },
  { code: "MTZ", labelEn: "Topical External Combination Pack Creams", labelFr: "Pack Combiné de Crèmes Externe Topique" },
  { code: "MV", labelEn: "Topical External Gels and Sols", labelFr: "Gels et Solutions Externe Topique" },
  { code: "MVA", labelEn: "Topical External Gels and Sols", labelFr: "Gels et Solutions Externe Topique" },
  { code: "MVL", labelEn: "Topical External Emulsion Gels", labelFr: "Gels d'Émulsion Externe Topique" },
  { code: "MVN", labelEn: "Topical External Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Externe Topique" },
  { code: "MVP", labelEn: "Topical External Metered-Dose Gels/Sols", labelFr: "Gels/Solutions Dose Mesurée Externe Topique" },
  { code: "MVW", labelEn: "Topical External Wash/Shower Gels", labelFr: "Gels de Lavage/Douche Externe Topique" },
  { code: "MVY", labelEn: "Topical External Other Gels/Sols", labelFr: "Autres Gels/Solutions Externe Topique" },
  { code: "MVZ", labelEn: "Topical External Combination Pack Gels/Sols", labelFr: "Pack Combiné de Gels/Solutions Externe Topique" },
  { code: "MW", labelEn: "Topical External Medicated Dressings", labelFr: "Pansements Médicamentés Externe Topique" },
  { code: "MWA", labelEn: "Topical External Plasters with Substance", labelFr: "Pansements avec Substance Externe Topique" },
  { code: "MWB", labelEn: "Topical External Cotton with Substance", labelFr: "Coton avec Substance Externe Topique" },
  { code: "MWC", labelEn: "Topical External Gauze or Fleece with Substance", labelFr: "Gaze ou Toison avec Substance Externe Topique" },
  { code: "MWD", labelEn: "Topical External Pads with Substance", labelFr: "Tampons avec Substance Externe Topique" },
  { code: "MWE", labelEn: "Topical External Tampons with Substance", labelFr: "Tampons avec Substance Externe Topique" },
  { code: "MWG", labelEn: "Topical External Bandages with Substance", labelFr: "Bandages avec Substance Externe Topique" },
  { code: "MWH", labelEn: "Topical External Sponges with Substance", labelFr: "Éponges avec Substance Externe Topique" },
  { code: "MWS", labelEn: "Topical External Poultices", labelFr: "Cataplasmes Externe Topique" },
  { code: "MWY", labelEn: "Topical External Other Medicated Dressings", labelFr: "Autres Pansements Médicamentés Externe Topique" },
  { code: "MWZ", labelEn: "Topical External Combination Pack Medicated Dressings", labelFr: "Pack Combiné de Pansements Médicamentés Externe Topique" },
  { code: "MY", labelEn: "Topical External Other Special Forms", labelFr: "Autres Formes Spéciales Externe Topique" },
  { code: "MYK", labelEn: "Topical External Styli and Cones Non-Rectal", labelFr: "Styli et Cones de Plaies Non-Rectal Externe Topique" },
  { code: "MYM", labelEn: "Topical External Sticks and Roll-Ons", labelFr: "Sticks et Roll-Ons Externe Topique" },
  { code: "MYP", labelEn: "Topical External Bone Cement with Substance", labelFr: "Ciment Osseux avec Substance Externe Topique" },
  { code: "MYS", labelEn: "Topical External Fumigation Candles", labelFr: "Bougies de Fumigation Externe Topique" },
  { code: "MYT", labelEn: "Topical External Foams", labelFr: "Mousses Externe Topique" },
  { code: "MYW", labelEn: "Topical External Solid Soaps/Bars", labelFr: "Savons/Bars Solides Externe Topique" },
  { code: "MYY", labelEn: "Topical External Other Special Forms", labelFr: "Autres Formes Spéciales Externe Topique" },
  { code: "MZ", labelEn: "Topical External Medical Aids", labelFr: "Aides Médicales Externe Topique" },
  { code: "MZA", labelEn: "Topical External Plasters without Substance", labelFr: "Pansements sans Substance Externe Topique" },
  { code: "MZB", labelEn: "Topical External Cotton without Substance", labelFr: "Coton sans Substance Externe Topique" },
  { code: "MZC", labelEn: "Topical External Gauze or Fleece without Substance", labelFr: "Gaze ou Toison sans Substance Externe Topique" },
  { code: "MZD", labelEn: "Topical External Pads without Substance", labelFr: "Tampons sans Substance Externe Topique" },
  { code: "MZE", labelEn: "Topical External Tampons without Substance", labelFr: "Tampons sans Substance Externe Topique" },
  { code: "MZG", labelEn: "Topical External Bandages without Substance", labelFr: "Bandages sans Substance Externe Topique" },
  { code: "MZH", labelEn: "Topical External Sponges without Substance", labelFr: "Éponges sans Substance Externe Topique" },
  { code: "MZJ", labelEn: "Topical External Tissue Absorbable Medical Aids", labelFr: "Aides Médicales Absorbables Externe Topique" },
  { code: "MZK", labelEn: "Topical External Gel and Colloid Dressings", labelFr: "Pansements de Gel et Colloïdes Externe Topique" },
  { code: "MZP", labelEn: "Topical External Bone Cements without Substance", labelFr: "Ciments Osseux sans Substance Externe Topique" },
  { code: "MZV", labelEn: "Topical External Diagnostic Tests Excluding Sticks", labelFr: "Tests de Diagnostic Excluant les Styli Externe Topique" },
  { code: "MZY", labelEn: "Topical External Other Medical Aids", labelFr: "Autres Aides Médicales Externe Topique" },
  { code: "N", labelEn: "Ophthalmic", labelFr: "Ophtalmique" },
  { code: "NAK", labelEn: "Ophthalmic Soluble Tablets", labelFr: "Comprimés Solubles Ophtalmiques" },
  { code: "NAZ", labelEn: "Ophthalmic Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Ophtalmiques" },
  { code: "ND", labelEn: "Ophthalmic Solid Special Forms", labelFr: "Formes Solides Spéciales Ophtalmiques" },
  { code: "NDN", labelEn: "Ocular Therapeutic Systems", labelFr: "Systèmes Thérapeutiques Oculaires" },
  { code: "NG", labelEn: "Ophthalmic Liquids", labelFr: "Liquides Ophtalmiques" },
  { code: "NGA", labelEn: "Ophthalmic Liquids", labelFr: "Liquides Ophtalmiques" },
  { code: "NGB", labelEn: "Ophthalmic Drops", labelFr: "Gouttes Ophtalmiques" },
  { code: "NGC", labelEn: "Ophthalmic Sprays Without Gas", labelFr: "Sprays Sans Gaz Ophtalmiques" },
  { code: "NGH", labelEn: "Ophthalmic Oils", labelFr: "Huiles Ophtalmiques" },
  { code: "NGJ", labelEn: "Ophthalmic Dry Suspensions/Syrups/Drops", labelFr: "Suspensions/Sirops/Gouttes Sèches Ophtalmiques" },
  { code: "NGK", labelEn: "Ophthalmic Suspensions", labelFr: "Suspensions Ophtalmiques" },
  { code: "NGN", labelEn: "Ophthalmic Unit Dose Liquids", labelFr: "Liquides Unidose Ophtalmiques" },
  { code: "NGP", labelEn: "Ophthalmic Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Ophtalmiques" },
  { code: "NGQ", labelEn: "Ophthalmic Preservative-Free Multi-Dose Liquids", labelFr: "Liquides Multidose Sans Conservateur Ophtalmiques" },
  { code: "NGS", labelEn: "Ophthalmic Lotions", labelFr: "Lotions Ophtalmiques" },
  { code: "NGZ", labelEn: "Ophthalmic Combination Pack Liquids", labelFr: "Pack Combiné de Liquides Ophtalmiques" },
  { code: "NH", labelEn: "Ophthalmic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Ophtalmiques" },
  { code: "NHA", labelEn: "Ophthalmic Pressurised Aerosols", labelFr: "Aérosols Pressurisés Ophtalmiques" },
  { code: "NM", labelEn: "Ophthalmic Ampoules", labelFr: "Ampoules Ophtalmiques" },
  { code: "NMA", labelEn: "Ophthalmic Ampoules", labelFr: "Ampoules Ophtalmiques" },
  { code: "NMB", labelEn: "Ophthalmic Dry Ampoules", labelFr: "Ampoules Sèches Ophtalmiques" },
  { code: "NN", labelEn: "Ophthalmic Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Ophtalmiques" },
  { code: "NNA", labelEn: "Ophthalmic Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Ophtalmiques" },
  { code: "NP", labelEn: "Ophthalmic Vials", labelFr: "Flacons Ophtalmiques" },
  { code: "NPA", labelEn: "Ophthalmic Vials", labelFr: "Flacons Ophtalmiques" },
  { code: "NPB", labelEn: "Ophthalmic Dry Vials", labelFr: "Flacons Sèches Ophtalmiques" },
  { code: "NPS", labelEn: "Ophthalmic Instillation Vials", labelFr: "Flacons d'Instillation Ophtalmiques" },
  { code: "NS", labelEn: "Ophthalmic Ointments", labelFr: "Onguent Ophtalmiques" },
  { code: "NSA", labelEn: "Ophthalmic Ointments", labelFr: "Onguent Ophtalmiques" },
  { code: "NSN", labelEn: "Ophthalmic Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Ophtalmiques" },
  { code: "NT", labelEn: "Ophthalmic Creams", labelFr: "Crèmes Ophtalmiques" },
  { code: "NTA", labelEn: "Ophthalmic Creams", labelFr: "Crèmes Ophtalmiques" },
  { code: "NV", labelEn: "Ophthalmic Gels/Sols", labelFr: "Gels/Solutions Ophtalmiques" },
  { code: "NVA", labelEn: "Ophthalmic Gels/Sols", labelFr: "Gels/Solutions Ophtalmiques" },
  { code: "NVB", labelEn: "Ophthalmic Gel Drops", labelFr: "Gouttes de Gel Ophtalmiques" },
  { code: "NVN", labelEn: "Ophthalmic Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Ophtalmiques" },
  { code: "NW", labelEn: "Ophthalmic Medicated Dressings", labelFr: "Pansements Médicamentés Ophtalmiques" },
  { code: "NWC", labelEn: "Ophthalmic Gauze or Fleece with Substance", labelFr: "Gaze ou Toison avec Substance Ophtalmiques" },
  { code: "NWD", labelEn: "Ophthalmic Pads with Substance", labelFr: "Tampons avec Substance Ophtalmiques" },
  { code: "NZ", labelEn: "Ophthalmic Medical Aids", labelFr: "Aides Médicales Ophtalmiques" },
  { code: "NZD", labelEn: "Ophthalmic Pads without Substance", labelFr: "Tampons sans Substance Ophtalmiques" },
  { code: "NZT", labelEn: "Ophthalmic Diagnostic Sticks", labelFr: "Tests de Diagnostic Ophtalmiques" },
  { code: "NZV", labelEn: "Ophthalmic Diagnostic Tests Excluding Sticks", labelFr: "Tests de Diagnostic Excluant les Styli Ophtalmiques" },
  { code: "NZY", labelEn: "Ophthalmic Other Medical Aids", labelFr: "Autres Aides Médicales Ophtalmiques" },
  { code: "P", labelEn: "Otic", labelFr: "Otique" },
  { code: "PG", labelEn: "Otic Liquids", labelFr: "Liquides Otique" },
  { code: "PGA", labelEn: "Otic Liquids", labelFr: "Liquides Otique" },
  { code: "PGB", labelEn: "Otic Drops", labelFr: "Gouttes Otique" },
  { code: "PGJ", labelEn: "Otic Dry Drops", labelFr: "Gouttes Sèches Otique" },
  { code: "PGK", labelEn: "Otic Suspensions", labelFr: "Suspensions Otique" },
  { code: "PGN", labelEn: "Otic Unit Dose Liquids", labelFr: "Liquides Unidose Otique" },
  { code: "PGP", labelEn: "Otic Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Otique" },
  { code: "PS", labelEn: "Otic Ointments", labelFr: "Onguent Otique" },
  { code: "PSA", labelEn: "Otic Ointments", labelFr: "Onguent Otique" },
  { code: "PT", labelEn: "Otic Creams", labelFr: "Crèmes Otique" },
  { code: "PTA", labelEn: "Otic Creams", labelFr: "Crèmes Otique" },
  { code: "PY", labelEn: "Otic Other Special Forms", labelFr: "Autres Formes Spéciales Otique" },
  { code: "PYK", labelEn: "Otic Styli and Wound Cones Non-Rectal", labelFr: "Styli et Cones de Plaies Non-Rectal Otique" },
  { code: "PYY", labelEn: "Otic Other Special Forms", labelFr: "Autres Formes Spéciales Otique" },
  { code: "Q", labelEn: "Nasal Topical", labelFr: "Nasal Topique" },
  { code: "QC", labelEn: "Nasal Topical Capsules", labelFr: "Capsules Nasal Topique" },
  { code: "QCA", labelEn: "Nasal Topical Capsules", labelFr: "Capsules Nasal Topique" },
  { code: "QCT", labelEn: "Nasal Topical Inhaler Capsules", labelFr: "Capsules d'Inhalation Nasal Topique" },
  { code: "QE", labelEn: "Nasal Topical Powders/Granules", labelFr: "Poudres/Granules Nasal Topique" },
  { code: "QEA", labelEn: "Nasal Topical Powders", labelFr: "Poudres Nasal Topique" },
  { code: "QEP", labelEn: "Nasal Topical Unit Dose Powders", labelFr: "Poudres Unidose Nasal Topique" },
  { code: "QG", labelEn: "Nasal Topical Liquids", labelFr: "Liquides Nasal Topique" },
  { code: "QGA", labelEn: "Nasal Topical Liquids", labelFr: "Liquides Nasal Topique" },
  { code: "QGB", labelEn: "Nasal Topical Drops", labelFr: "Gouttes Nasal Topique" },
  { code: "QGC", labelEn: "Nasal Topical Sprays without Gas", labelFr: "Sprays Sans Gaz Nasal Topique" },
  { code: "QGE", labelEn: "Nasal Topical Liquid Inhalations", labelFr: "Inhalations Liquides Nasal Topique" },
  { code: "QGH", labelEn: "Nasal Topical Oils", labelFr: "Huiles Nasal Topique" },
  { code: "QGK", labelEn: "Nasal Topical Suspensions", labelFr: "Suspensions Nasal Topique" },
  { code: "QGL", labelEn: "Nasal Topical Emulsions", labelFr: "Émulsions Nasal Topique" },
  { code: "QGN", labelEn: "Nasal Topical Unit Dose Liquids", labelFr: "Liquides Unidose Nasal Topique" },
  { code: "QGP", labelEn: "Nasal Topical Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Nasal Topique" },
  { code: "QGZ", labelEn: "Nasal Topical Combination Pack Liquids", labelFr: "Pack Combiné de Liquides Nasal Topique" },
  { code: "QH", labelEn: "Nasal Topical Pressurised Aerosols", labelFr: "Aérosols Pressurisés Nasal Topique" },
  { code: "QHA", labelEn: "Nasal Topical Pressurised Aerosols", labelFr: "Aérosols Pressurisés Nasal Topique" },
  { code: "QHP", labelEn: "Nasal Topical Metered Dose Aerosols", labelFr: "Aérosols Dose Mesurée Nasal Topique" },
  { code: "QM", labelEn: "Nasal Topical Ampoules", labelFr: "Ampoules Nasal Topique" },
  { code: "QMA", labelEn: "Nasal Topical Ampoules", labelFr: "Ampoules Nasal Topique" },
  { code: "QN", labelEn: "Nasal Topical Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Nasal Topique" },
  { code: "QNA", labelEn: "Nasal Topical Pre-Filled Syringes", labelFr: "Seringues Prêtes à l'Emploi Nasal Topique" },
  { code: "QS", labelEn: "Nasal Topical Ointments", labelFr: "Onguent Nasal Topique" },
  { code: "QSA", labelEn: "Nasal Topical Ointments", labelFr: "Onguent Nasal Topique" },
  { code: "QSL", labelEn: "Nasal Topical Emulsion Ointments", labelFr: "Onguent d'Émulsion Nasal Topique" },
  { code: "QT", labelEn: "Nasal Topical Creams", labelFr: "Crèmes Nasal Topique" },
  { code: "QTA", labelEn: "Nasal Topical Creams", labelFr: "Crèmes Nasal Topique" },
  { code: "QV", labelEn: "Nasal Topical Gels and Sols", labelFr: "Gels et Solutions Nasal Topique" },
  { code: "QVA", labelEn: "Nasal Topical Gels and Sols", labelFr: "Gels et Solutions Nasal Topique" },
  { code: "QVN", labelEn: "Nasal Topical Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Nasal Topique" },
  { code: "QY", labelEn: "Nasal Topical Other Special Forms", labelFr: "Autres Formes Spéciales Nasal Topique" },
  { code: "QYM", labelEn: "Nasal Topical Sticks and Roll-Ons", labelFr: "Sticks et Roll-Ons Nasal Topique" },
  { code: "R", labelEn: "Lung Administration", labelFr: "Administration Pulmonaire" },
  { code: "RC", labelEn: "Lung Administration Capsules", labelFr: "Capsules Administration Pulmonaire" },
  { code: "RCT", labelEn: "Lung Administration Inhaler Capsules", labelFr: "Capsules d'Inhalation Administration Pulmonaire" },
  { code: "RE", labelEn: "Lung Administration Powders/Granules", labelFr: "Poudres/Granules Administration Pulmonaire" },
  { code: "REM", labelEn: "Lung Administration Unit Dose Powder Inhaler Non-Refillable", labelFr: "Inhalateurs Unidose Non-Rechargeables Administration Pulmonaire" },
  { code: "REN", labelEn: "Lung Administration Unit Dose Powder Inhaler Refillable", labelFr: "Inhalateurs Unidose Rechargeables Administration Pulmonaire" },
  { code: "REP", labelEn: "Lung Administration Metered-Dose Powder Inhaler", labelFr: "Inhalateurs de Poudre Dose Mesurée Administration Pulmonaire" },
  { code: "RG", labelEn: "Lung Administration Liquids", labelFr: "Liquides Administration Pulmonaire" },
  { code: "RGE", labelEn: "Lung Administration Liquid for Inhalation", labelFr: "Liquides pour Inhalation Administration Pulmonaire" },
  { code: "RGN", labelEn: "Lung Administration Unit Dose Liquids", labelFr: "Liquides Unidose Administration Pulmonaire" },
  { code: "RGP", labelEn: "Lung Administration Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Administration Pulmonaire" },
  { code: "RH", labelEn: "Lung Administration Pressurised Aerosols", labelFr: "Aérosols Pressurisés Administration Pulmonaire" },
  { code: "RHC", labelEn: "Lung Administration Pressurised Powders", labelFr: "Poudres Pressurisées Administration Pulmonaire" },
  { code: "RHM", labelEn: "Lung Administration Breath-Actuated Metered-Dose Inhaler", labelFr: "Inhalateurs Dose Mesurée à Activation Respiratoire Administration Pulmonaire" },
  { code: "RHN", labelEn: "Lung Administration Breath-Actuated CFC-Free Metered-Dose Inhaler", labelFr: "Inhalateurs Sans CFC à Activation Respiratoire Administration Pulmonaire" },
  { code: "RHP", labelEn: "Lung Administration Metered-Dose Inhaler", labelFr: "Inhalateurs Dose Mesurée Administration Pulmonaire" },
  { code: "RHQ", labelEn: "Lung Administration CFC-Free Metered-Dose Inhaler", labelFr: "Inhalateurs Sans CFC Dose Mesurée Administration Pulmonaire" },
  { code: "RY", labelEn: "Lung Administration Other Special Forms", labelFr: "Autres Formes Spéciales Administration Pulmonaire" },
  { code: "RYJ", labelEn: "Lung Administration Cigarettes", labelFr: "Cigarettes Administration Pulmonaire" },
  { code: "T", labelEn: "Vaginal", labelFr: "Vaginal" },
  { code: "TA", labelEn: "Vaginal Tablets", labelFr: "Comprimés Vaginal" },
  { code: "TAA", labelEn: "Vaginal Tablets", labelFr: "Comprimés Vaginal" },
  { code: "TAH", labelEn: "Vaginal Effervescent Tablets", labelFr: "Comprimés Effervescents Vaginal" },
  { code: "TAK", labelEn: "Vaginal Soluble Tablets", labelFr: "Comprimés Solubles Vaginal" },
  { code: "TAY", labelEn: "Vaginal Other Tablets", labelFr: "Autres Comprimés Vaginal" },
  { code: "TAZ", labelEn: "Vaginal Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Vaginal" },
  { code: "TC", labelEn: "Vaginal Capsules", labelFr: "Capsules Vaginal" },
  { code: "TCA", labelEn: "Vaginal Capsules", labelFr: "Capsules Vaginal" },
  { code: "TE", labelEn: "Vaginal Powders/Granules", labelFr: "Poudres/Granules Vaginal" },
  { code: "TEA", labelEn: "Vaginal Powders", labelFr: "Poudres Vaginal" },
  { code: "TEK", labelEn: "Vaginal Soluble Powders", labelFr: "Poudres Solubles Vaginal" },
  { code: "TEP", labelEn: "Vaginal Unit Dose Powders", labelFr: "Poudres Unidose Vaginal" },
  { code: "TG", labelEn: "Vaginal Liquids", labelFr: "Liquides Vaginal" },
  { code: "TGA", labelEn: "Vaginal Liquids", labelFr: "Liquides Vaginal" },
  { code: "TGL", labelEn: "Vaginal Liquid Emulsions", labelFr: "Émulsions Liquides Vaginal" },
  { code: "TGN", labelEn: "Vaginal Unit Dose Liquids", labelFr: "Liquides Unidose Vaginal" },
  { code: "TGP", labelEn: "Vaginal Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Vaginal" },
  { code: "TGS", labelEn: "Vaginal Lotions", labelFr: "Lotions Vaginal" },
  { code: "TGW", labelEn: "Vaginal Liquid Soaps/Washes", labelFr: "Savons/Lavages Liquides Vaginal" },
  { code: "TH", labelEn: "Vaginal Pressurised Aerosols", labelFr: "Aérosols Pressurisés Vaginal" },
  { code: "THA", labelEn: "Vaginal Pressurised Aerosols", labelFr: "Aérosols Pressurisés Vaginal" },
  { code: "THT", labelEn: "Vaginal Pressurised Foams", labelFr: "Mousses Pressurisées Vaginal" },
  { code: "TL", labelEn: "Vaginal Suppositories", labelFr: "Suppositoires Vaginal" },
  { code: "TLS", labelEn: "Vaginal Suppositories", labelFr: "Suppositoires Vaginal" },
  { code: "TLZ", labelEn: "Vaginal Combination Pack Suppositories", labelFr: "Pack Combiné de Suppositoires Vaginal" },
  { code: "TM", labelEn: "Vaginal Ampoules", labelFr: "Ampoules Vaginal" },
  { code: "TMA", labelEn: "Vaginal Ampoules", labelFr: "Ampoules Vaginal" },
  { code: "TS", labelEn: "Vaginal Ointments", labelFr: "Onguent Vaginal" },
  { code: "TSA", labelEn: "Vaginal Ointments", labelFr: "Onguent Vaginal" },
  { code: "TSB", labelEn: "Vaginal Pastes", labelFr: "Pâte Vaginal" },
  { code: "TSN", labelEn: "Vaginal Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Vaginal" },
  { code: "TT", labelEn: "Vaginal Creams", labelFr: "Crèmes Vaginal" },
  { code: "TTA", labelEn: "Vaginal Creams", labelFr: "Crèmes Vaginal" },
  { code: "TTN", labelEn: "Vaginal Unit Dose Creams", labelFr: "Crèmes Unidose Vaginal" },
  { code: "TTZ", labelEn: "Vaginal Combination Pack Creams", labelFr: "Pack Combiné de Crèmes Vaginal" },
  { code: "TV", labelEn: "Vaginal Gels and Sols", labelFr: "Gels et Solutions Vaginal" },
  { code: "TVA", labelEn: "Vaginal Gels and Sols", labelFr: "Gels et Solutions Vaginal" },
  { code: "TVN", labelEn: "Vaginal Unit Dose Gels/Sols", labelFr: "Gels/Solutions Unidose Vaginal" },
  { code: "TW", labelEn: "Vaginal Medic Dressings", labelFr: "Pansements Médicamentés Vaginal" },
  { code: "TWE", labelEn: "Vaginal Tampons with Substance", labelFr: "Tampons avec Substance Vaginal" },
  { code: "TWH", labelEn: "Vaginal Sponges with Substance", labelFr: "Éponges avec Substance Vaginal" },
  { code: "TWY", labelEn: "Vaginal Other Medicated Dressings", labelFr: "Autres Pansements Médicamentés Vaginal" },
  { code: "TY", labelEn: "Vaginal Other Special Forms", labelFr: "Autres Formes Spéciales Vaginal" },
  { code: "TYQ", labelEn: "Vaginal Mechanical Pessaries with Substance", labelFr: "Pessaires Mécaniques avec Substance Vaginal" },
  { code: "TYR", labelEn: "Vaginal Intra Uterine Devices", labelFr: "Dispositifs Intra-Utérins Vaginal" },
  { code: "TYT", labelEn: "Vaginal Foams", labelFr: "Mousses Vaginal" },
  { code: "TYY", labelEn: "Vaginal Other Special Forms", labelFr: "Autres Formes Spéciales Vaginal" },
  { code: "TZ", labelEn: "Vaginal Medical Aids", labelFr: "Aides Médicales Vaginal" },
  { code: "TZD", labelEn: "Vaginal Pads without Substance", labelFr: "Tampons sans Substance Vaginal" },
  { code: "TZE", labelEn: "Vaginal Tampons without Substance", labelFr: "Tampons sans Substance Vaginal" },
  { code: "TZQ", labelEn: "Vaginal Mechanical Pessaries without Substance", labelFr: "Pessaires Mécaniques sans Substance Vaginal" },
  { code: "V", labelEn: "Non-Human Use and Others", labelFr: "Usage Non Humain et Autres" },
  { code: "VA", labelEn: "Non-Human Use Tablets", labelFr: "Comprimés Usage Non Humain" },
  { code: "VAA", labelEn: "Non-Human Use Tablets", labelFr: "Comprimés Usage Non Humain" },
  { code: "VAH", labelEn: "Non-Human Use Effervescent Tablets", labelFr: "Comprimés Effervescents Usage Non Humain" },
  { code: "VAK", labelEn: "Non-Human Use Soluble Tablets", labelFr: "Comprimés Solubles Usage Non Humain" },
  { code: "VAZ", labelEn: "Non-Human Use Combination Pack Tablets", labelFr: "Pack Combiné de Comprimés Usage Non Humain" },
  { code: "VE", labelEn: "Non-Human Use Powders/Granules", labelFr: "Poudres/Granules Usage Non Humain" },
  { code: "VEA", labelEn: "Non-Human Use Powders", labelFr: "Poudres Usage Non Humain" },
  { code: "VEB", labelEn: "Non-Human Use Granules", labelFr: "Granules Usage Non Humain" },
  { code: "VED", labelEn: "Non-Human Use Solid Substance", labelFr: "Substances Solides Usage Non Humain" },
  { code: "VEH", labelEn: "Non-Human Use Effervescent Powders/Granules", labelFr: "Poudres/Granules Effervescentes Usage Non Humain" },
  { code: "VEK", labelEn: "Non-Human Use Soluble Powders", labelFr: "Poudres Solubles Usage Non Humain" },
  { code: "VEP", labelEn: "Non-Human Use Unit Dose Powders", labelFr: "Poudres Unidose Usage Non Humain" },
  { code: "VG", labelEn: "Non-Human Use Liquids", labelFr: "Liquides Usage Non Humain" },
  { code: "VGA", labelEn: "Non-Human Use Liquids", labelFr: "Liquides Usage Non Humain" },
  { code: "VGB", labelEn: "Non-Human Use Drops", labelFr: "Gouttes Usage Non Humain" },
  { code: "VGC", labelEn: "Non-Human Use Sprays without Gas", labelFr: "Sprays Sans Gaz Usage Non Humain" },
  { code: "VGN", labelEn: "Non-Human Use Unit Dose Liquids", labelFr: "Liquides Unidose Usage Non Humain" },
  { code: "VGP", labelEn: "Non-Human Use Metered-Dose Liquids", labelFr: "Liquides Dose Mesurée Usage Non Humain" },
  { code: "VH", labelEn: "Non-Human Use Pressurised Aerosols", labelFr: "Aérosols Pressurisés Usage Non Humain" },
  { code: "VHA", labelEn: "Non-Human Use Pressurised Aerosols", labelFr: "Aérosols Pressurisés Usage Non Humain" },
  { code: "VHT", labelEn: "Non-Human Use Pressurised Foams", labelFr: "Mousses Pressurisées Usage Non Humain" },
  { code: "VM", labelEn: "Non-Human Use Ampoules", labelFr: "Ampoules Usage Non Humain" },
  { code: "VMA", labelEn: "Non-Human Use Ampoules", labelFr: "Ampoules Usage Non Humain" },
  { code: "VMB", labelEn: "Non-Human Use Dry Ampoules", labelFr: "Ampoules Sèches Usage Non Humain" },
  { code: "VP", labelEn: "Non-Human Use Vials", labelFr: "Flacons Usage Non Humain" },
  { code: "VPA", labelEn: "Non-Human Use Vials", labelFr: "Flacons Usage Non Humain" },
  { code: "VS", labelEn: "Non-Human Use Ointments", labelFr: "Onguent Usage Non Humain" },
  { code: "VSB", labelEn: "Non-Human Use Pastes", labelFr: "Pâte Usage Non Humain" },
  { code: "VSN", labelEn: "Non-Human Use Unit Dose Ointments and Pastes", labelFr: "Onguent et Pâtes Unidose Usage Non Humain" },
  { code: "VT", labelEn: "Non-Human Use Creams", labelFr: "Crèmes Usage Non Humain" },
  { code: "VTA", labelEn: "Non-Human Use Creams", labelFr: "Crèmes Usage Non Humain" },
  { code: "VTN", labelEn: "Non-Human Use Unit Dose Creams", labelFr: "Crèmes Unidose Usage Non Humain" },
  { code: "VV", labelEn: "Non-Human Use Gels and Sols", labelFr: "Gels et Solutions Usage Non Humain" },
  { code: "VVA", labelEn: "Non-Human Use Gels and Sols", labelFr: "Gels et Solutions Usage Non Humain" },
  { code: "VW", labelEn: "Non-Human Use Medicated Dressing", labelFr: "Pansements Médicamentés Usage Non Humain" },
  { code: "VWC", labelEn: "Non-Human Use Gauze or Fleece with Substance", labelFr: "Gaze ou Toison avec Substance Usage Non Humain" },
  { code: "VY", labelEn: "Non-Human Use Other Special Forms", labelFr: "Autres Formes Spéciales Usage Non Humain" },
  { code: "VYY", labelEn: "Non-Human Use Unknown", labelFr: "Usage Non Humain Inconnu" },
  { code: "VZ", labelEn: "Non-Human Use Medical Use", labelFr: "Aides Médicales Usage Non Humain" },
  { code: "VZT", labelEn: "Non-Human Use Diagnostic Sticks", labelFr: "Tests de Diagnostic Usage Non Humain" },
  { code: "VZV", labelEn: "Non-Human Use Diagnostic Test Excluding Sticks", labelFr: "Tests de Diagnostic Excluant les Styli Usage Non Humain" },
  { code: "VZY", labelEn: "Non-Human Use Other Medical Aids", labelFr: "Autres Aides Médicales Usage Non Humain" },
  { code: "Z", labelEn: "Unknown", labelFr: "Inconnu" },
  { code: "ZE", labelEn: "Unknown Powders/Granules", labelFr: "Poudres/Granules Inconnu" },
  { code: "ZEA", labelEn: "Unknown Powders", labelFr: "Poudres Inconnu" },
  { code: "ZEB", labelEn: "Unknown Granules", labelFr: "Granules Inconnu" },
  { code: "ZEY", labelEn: "Unknown Other Powders/Granules", labelFr: "Autres Poudres/Granules Inconnu" },
  { code: "ZG", labelEn: "Unknown Liquids", labelFr: "Liquides Inconnu" },
  { code: "ZGA", labelEn: "Unknown Liquids", labelFr: "Liquides Inconnu" },
  { code: "ZGH", labelEn: "Unknown Oils", labelFr: "Huiles Inconnu" },
  { code: "ZY", labelEn: "Unknown Other Special Forms", labelFr: "Autres Formes Spéciales Inconnu" },
  { code: "ZYX", labelEn: "Unknown Promotional Packs", labelFr: "Packs Promotionnels Inconnu" },
  { code: "ZYY", labelEn: "Unknown", labelFr: "Inconnu" },
  { code: "ZZ", labelEn: "Unknown Medical Aids", labelFr: "Aides Médicales Inconnu" },
  { code: "ZZZ", labelEn: "Unknown Combination Pack Medical Aids", labelFr: "Pack Combiné d'Aides Médicales Inconnu" },
]

// sorted longest-French-label-first for greedy matching
const SORTED = [...NFC_CODES].sort((a, b) => b.labelFr.length - a.labelFr.length)

function norm(s: string): string {
  return s.toLowerCase()
    .normalize("NFD").replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9 ]/g, " ")
    .replace(/\s+/g, " ").trim()
}

export function detectNfcCode(formName: string): { code: string; labelFr: string; labelEn: string; confidence: "high" | "medium" | "low" } | null {
  if (!formName) return null
  const n = norm(formName)
  for (const nfc of SORTED) {
    const nfr = norm(nfc.labelFr)
    const nen = norm(nfc.labelEn)
    if (nfr && n.includes(nfr)) return { ...nfc, confidence: "high" }
    if (nen && n.includes(nen)) return { ...nfc, confidence: "medium" }
  }
  // Try word-by-word partial match on single-word key terms
  const words = n.split(" ").filter(w => w.length > 4)
  for (const nfc of SORTED) {
    const nfr = norm(nfc.labelFr)
    if (words.some(w => nfr.includes(w))) return { ...nfc, confidence: "low" }
  }
  return null
}
